name: GrandCraftAuto
version: 1.0
main: we.Heiden.gca.core.Main
description: Do you wanna play GTA? You can do it now on Minecraft!
author: Heiden Team

commands:
    test:
        usage: /<command>
        description: test!
    GarageArea:
        usage: /<command>
        description: Set the garage`s Area!
        aliases: [garea, ga, garagea, setgaragearea, sga, sgarea, setgarea, setgaragea, sgaragea, setgarea]
    setGarageEntry:
        usage: /<command>
        description: Set some entries to the garage!
        aliases: [sge, gentry, entry, setgentry, garageentry, setgarage, setgaragee, garagee, sgaragee, sgentry, setge]
    GarageWarp:
        usage: /<command>
        description: Set a Warp!
        aliases: [sgw, gwarp, setgwarp, garagewarp, setgaragew, garagew, sgaragew, sgwarp, setgw]
        