name: GrandCraftAuto
version: 1.0
main: we.Heiden.gca.core.Main
description: Do you wanna play GTA? You can do it now on Minecraft!
author: Heiden Team

commands:
    test:
        usage: /<command>
        description: test!
    GarageSlot:
        usage: /<command>
        description: Set a car`s slot on the garage!
        aliases: [gslot, gs, garages, setgarageslot, sgs, sgslot, setgslot, setgarages, sgarages, setgslot]
    setGarageEntry:
        usage: /<command>
        description: Set some entries to the garage!
        aliases: [sge, gentry, entry, setgentry, garageentry, setgarage, setgaragee, garagee, sgaragee, sgentry, setge]
    GarageWarp:
        usage: /<command>
        description: Set a Warp!
        aliases: [sgw, gwarp, setgwarp, garagewarp, setgaragew, garagew, sgaragew, sgwarp, setgw]
    GarageExit:
        usage: /<command>
        description: Set some entries to the garage!
        aliases: [sgl, ge, gexit, setgexit, garageexit, setgarageleave, setgaragel, garagel, sgaragel, sgexit, setgl]
    Store:
        usage: /<command>
        description: Private Command
        