name: GrandCraftAuto
version: 1.0
main: we.Heiden.gca.core.Main
description: Do you wanna play GTA? You can do it now on Minecraft!
author: Heiden Team

commands:
    items:
    GarageSlot:
        aliases: [gslot, gs, garages, setgarageslot, sgs, sgslot, setgslot, setgarages, sgarages, setgslot]
    setGarageEntry:
        aliases: [sge, gentry, entry, setgentry, garageentry, setgarage, setgaragee, garagee, sgaragee, sgentry, setge]
    GarageWarp:
        aliases: [sgw, gwarp, setgwarp, garagewarp, setgaragew, garagew, sgaragew, sgwarp, setgw]
    GarageExit:
        aliases: [sgl, ge, gexit, setgexit, garageexit, setgarageleave, setgaragel, garagel, sgaragel, sgexit, setgl]
    Store:
    AirportSpawn:
        aliases: [as]
    AirportArea:
        aliases: [aa]
    TutoSpawn:
        aliases: [ts]
    setHospital:
        aliases: [sh]
    HospitalWarp:
        aliases: [hw]
    setRespawn:
        aliases: [sr, hr]
    setNpc:
        aliases: [sn]
    setHome:
        aliases: [shome, seth]
    Home:
        aliases: [h]
    Trade:
        aliases: [t]
    Contact:
        aliases: [agenda]